#!/bin/bash

# Install necessary libraries
sudo apt install libssl-dev
sudo sh -c "echo 'deb http://security.ubuntu.com/ubuntu xenial-security main' >> /etc/apt/sources.list"
sudo apt update
sudo apt install libssl1.0.0

# Get the password using gdb
password=$(gdb -q -ex 'disassemble main' -ex 'x/s 0x804885c' -ex 'quit' crackme2 | grep -oP '(?<=:\s).*$')

# Write the password to a file
echo -n "$password" > password.txt

